# Generated by Django 5.0.6 on 2024-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0002_subscriber_delete_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
