# Generated by Django 5.0.6 on 2024-06-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterapp', '0003_subscriber_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
